### ISSUE TITLE
Building/Removing Sails

### ISSUE THREAD

**Issue by 5FearL1fe** [zolantris/ValheimMods#102]
### What happened?

Firstly, i have no idea how to build the custom sails properly, I havent seen anything that tells me, and i also have no idea how to remove them when I do manage to build one. Because wheni right click it, it jsut removes the object behind it. And i cant remove the sails!!!

### Log outputs

```txt
Not the problem
```

### Environment

```markdown
OS:
- **OS**: Windows 11 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: Major.Minor.Patch
```

**Comment by zolantris** [comment]
Probably a triangle sail issue. Should be fixed in >=2.4.1 but if not. `forcedelete 5 MBSail` should work if near the sail..
