### ISSUE TITLE
No Custom Sail option since updating mod

### ISSUE THREAD

**Issue by Energeey** [zolantris/ValheimMods#118]
### What happened?

Custom Sail is missing from the build menu.

![image](https://github.com/user-attachments/assets/9193a75e-c696-4310-827b-4b1f0e097f95)

### Steps to reproduce

Updated to the latest version of ValheimRaft

### Log outputs

```txt
[Warning:Jotunn.Managers.PieceManager] [ValheimRAFT] Skipping piece MBSailCreator_3: Mock Material 'Custom/Piece' could not be resolved. GameObject with name 'Custom/Piece' was not found.
[Warning:Jotunn.Managers.PieceManager] [ValheimRAFT] Skipping piece MBSailCreator_4: Mock Material 'Custom/Piece' could not be resolved. GameObject with name 'Custom/Piece' was not found.
```

### Environment

```markdown
OS:
- **OS**: Windows 11 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: Major.Minor.Patch
```

**Comment by zolantris** [comment]
I'll look at this soon. What raft version? Guessing 2.2.2.

**Comment by Energeey** [comment]
Correct. Installed through r2modman. 



    On Tuesday, July 23, 2024 at 12:59:39 AM CDT, ***@***.*** ***@***.***> wrote:  
 
 


I'll look at this soon. What raft version? Guessing 2.2.2.

**Comment by zolantris** [comment]
#120 fixes this.
