### ISSUE TITLE
A small error in the code, in the localization key.

### ISSUE THREAD

**Issue by lijspoop** [zolantris/ValheimMods#126]
https://github.com/zolantris/ValheimMods/blob/6ea46882655e5264d8e48eed2c23ec0676bee702/src/ValheimVehicles/ValheimVehicles.Prefabs/PrefabRegistryHelpers.cs#L309

Missing `$` at the beginning of the string

`$"$valheim_vehicles_hull_center_desc {ironMatDesc}"`

**Comment by zolantris** [comment]
Thanks, I believe it's fixed in a unstable branch. But at least we can track it here now. Good catch!

I'll try to get this fixed in next update. 

Long term hoping to add translation injection to parse the json file to see if a dollar sign is missing for something that looks like a key.

Would be a "build" test.

**Comment by lijspoop** [comment]
The same mistake
![image](https://github.com/user-attachments/assets/811b6c59-c7ae-4b8e-88bd-bb176300ae8d)

https://github.com/zolantris/ValheimMods/blob/6ea46882655e5264d8e48eed2c23ec0676bee702/src/ValheimVehicles/ValheimVehicles.Prefabs/PrefabRegistryHelpers.cs#L83-L85

---

And while reviewing the code, I had two questions: 
1. Why use a ternary operator in line 215, since there is no such check in line 217?
https://github.com/zolantris/ValheimMods/blob/6ea46882655e5264d8e48eed2c23ec0676bee702/src/ValheimVehicles/ValheimVehicles.Prefabs/Registry/SailPrefabs.cs#L213-L219

I think that line 215 can be deleted (by removing the unnecessary creation of a variable), and it should turn out something like this:

```csharp
 var piece = prefab.AddComponent<Piece>(); 
 piece.m_name = $"$mb_sail_{sailCount}"; 
 piece.m_description = $"$mb_sail_{sailCount}_desc"; 
 piece.m_placeEffect = LoadValheimAssets.woodFloorPiece.m_placeEffect; 
```

2. Also, why use "mb_sail" if it is already used by another method (`RegisterCustomSail`) of creating a sail, moreover, it is not found anywhere in the release?
https://github.com/zolantris/ValheimMods/blob/6ea46882655e5264d8e48eed2c23ec0676bee702/src/ValheimVehicles/ValheimVehicles.Prefabs/Registry/SailPrefabs.cs#L174-L175

Most likely, this can be seen somewhere else in the code, but it doesn't hurt to ask at least about it.

**Comment by lijspoop** [comment]
> Thanks, I believe it's fixed in a unstable branch. But at least we can track it here now. Good catch!
> 
> I'll try to get this fixed in next update.
> 
> Long term hoping to add translation injection to parse the json file to see if a dollar sign is missing for something that looks like a key.
> 
> Would be a "build" test.

Is it possible to do it differently? For example, generate a translation file when "build".

**Comment by lijspoop** [comment]
try using this method to avoid something like this; it adds a `$` symbol to the beginning of a translation key if it isn't already there. For example, the string `"valheim_vehicles_ram_stake valheim_vehicles_material_tier3"` will be transformed into `"$valheim_vehicles_ram_stake $valheim_vehicles_material_tier3"`.

```csharp
  public static string NormalizeTranslationKeys(string input)
  {
    return Regex.Replace(input, @"([\$]?\w+_+\w+)", match =>
    {
      var currentMatch = match.Value;
      if (!currentMatch.StartsWith("$"))
        currentMatch = "$" + currentMatch;
      return currentMatch;
    });
  }
```

for example, you can use it here:
https://github.com/zolantris/ValheimMods/blob/ed67ed1f3d93c70bafdd4e0f55f16d34011fa44b/src/ValheimVehicles/ValheimVehicles.Prefabs/PrefabRegistryHelpers.cs#L20-L25

by doing this:
```csharp
public struct PieceData
{
    private string _name;
    private string _description;
    
    public string Name
    {
        get => _name;
        set => _name = NormalizeTranslationKeys(value);
    }

    public string Description
    {
        get => _description;
        set => _description = NormalizeTranslationKeys(value);
    }
    
    public Sprite Icon;
}
```
