### ISSUE TITLE
Large rafts get teleported upward when near shores which will yeet players into space.

### ISSUE THREAD

**Issue by Oroborius** [zolantris/ValheimMods#127]
### What happened?

Title. Built a large boat and now I can't bring it to the shore.

### Steps to reproduce

Build a large boat
Go near shore
Boat gets teleported up and anchored
You possibly die.

### Log outputs

```txt
https://pastebin.com/msXrmDt9
```

### Environment

```markdown
OS:
- **OS**: Arch Linux
- **Graphics**: Vulkan
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.20.3
- **ValheimRAFT**: 2.2.3
```

**Comment by zolantris** [comment]
Turn off the autoFixPosition. It's there to help, but there is a center point bug causing older ships center points to never shift so they get inaccurate

**Comment by Oroborius** [comment]
Will test it out next time I play. Thanks for the response. :-)

**Comment by zolantris** [comment]
Is this fixed in 2.2.4?

**Comment by Oroborius** [comment]
> Is this fixed in 2.2.4?

I am unsure. I have disabled the autoFixPosition which actually entirely solved the issue I was having since the day you mentioned it to me however I haven't actually tested with the option re-enabled as of yet.

**Comment by zolantris** [comment]
Don't do it lol. Though I think it's hard coded off for now even if flipped on.

When i get time I'll add the position fixed so the boat ball is always centered. Once that happens this issue will go away too.

**Comment by zolantris** [comment]
Done, 2.4.1+
