### ISSUE TITLE
[Physics issues] sailing not working upwind temp solution

### ISSUE THREAD

**Issue by FrederickEngelhardt** [zolantris/ValheimMods#152]
### Affected Mod

ValheimRAFT

### What happened? 🤔

Hello everyone for now in 2.4.1 you may have noticed that sailing does not work well with default config. Please do the following, install the config manager then change the damping values to 1.0 for water vehicles.

## workaround

go to config menu

set these values

waterSidewaysDamping = 1
waterAngularDamping = 1
waterDamping = 1

Noting that all the damping values on water surface should be 0.5 to be safe but realistic..but I set it to 0.05 which was way too low during publish.

find out more about config here https://github.com/zolantris/ValheimMods/tree/main/src/ValheimRAFT#config

Underwater has sailing power extremely low. You can increase it if you want. Rudder power works fully.

**Comment by EthanWS6** [comment]
I was having an issue where the wind was aggressively pushing my boat in the direction the wind itself was moving. It was to the point that the closest I could get to sailing straight was about a 45 degree angle. Will this help this issue? 

Thank you!

**Comment by zolantris** [comment]
#159 fixes this. It's included in 2.4.3 release.
