### ISSUE TITLE
Cant raise anchor

### ISSUE THREAD

**Issue by Amaradu** [zolantris/ValheimMods#158]
### Affected Mod

ValheimRAFT

### What happened? 🤔

Trying to sail ship I cant raise ship anchor, that doesn't allow for ship to move.
Singleplayer and multiplayer same issue. Mostly we play MP and mine friend can raise/lower anchor and control ship.
Tired to get off and on steering, going far away and come back, relogging to server/map, change hotkey to H and then still didn't work. Relaunch game, reinstall mods, use friends r2modman code for mods, restart pc, delete all mods and valheim restart pc and reinstall. Tied all keys on keyboard.

After some testing friend raised anchor and gave control to me, then I could change speed of the ship, but cant lower anchor.
 
To mod I'm using R2modman.

### Steps to reproduce 🔄

1. Load map/into server.
2. Go to ship
3. Interact with steering wheel
4. Press raise anchor hotkey(LeftShift/H/Space)
5. Anchor docent raise and cant control ship speed.

### Vehicle Info 🚗

[Message:ValheimVehicles.ConsoleCommands.VehicleCommands] ================ ValheimRaft/Vehicles report-info START ================
-1
vehiclePieces, -1
vehiclePiecesCount, piece_workbench(Clone),ValheimVehicles_Ship_Hull_Rib_Corner_left_Wood(Clone),ValheimVehicles_Ship_Hull_Rib_Wood(Clone),ValheimVehicles_Ship_Hull_Rib_Wood(Clone),ValheimVehicles_Ship_Hull_Rib_Corner_right_Wood(Clone),ValheimVehicles_Ship_Hull_Rib_Wood(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),MBBoardingRamp(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Ship_Hull_Rib_Wood(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_ShipSteeringWheel(Clone),ValheimVehicles_Ship_Hull_Wood(Clone),MBKarveMast(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Ship_Hull_Prow_Wood_2x2(Clone),ValheimVehicles_Ship_Hull_Wood(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),MBVikingShipMast(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),MBKarveMast(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Ship_Hull_Prow_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_4x4(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_ShipRudderAdvanced_Tail_Iron(Clone),MBBoardingRamp(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Ship_Hull_Rib_Wood(Clone),ValheimVehicles_Ship_Hull_Rib_Wood(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Ship_Hull_Rib_Corner_right_Wood(Clone),ValheimVehicles_Ship_Hull_Rib_Wood(Clone),ValheimVehicles_Hull_Slab_Wood_2x2(Clone),ValheimVehicles_Ship_Hull_Rib_Wood(Clone),ValheimVehicles_Ship_Hull_Rib_Corner_left_Wood(Clone)
PendingPiecesState Complete
vehiclePendingPieces: None
vehiclePendingPiecesCount, -1
playerPosition: (-90.66, 32.71, 973.04)
PlayersOnVehicle: Blue
vehiclePosition (-80.47, 28.71, 984.87)
PlayerProfile location: /characters/
Player.log location: /characters/Player.log.fch
WorldFolder location(may be N/A): /worlds
================ ValheimRaft/Vehicles report-info END ================

Logs:
[Player.log](https://github.com/user-attachments/files/17933673/Player.log)
[LogOutput.log](https://github.com/user-attachments/files/17933698/LogOutput.log)

### Log Outputs 📜

```txt
Added in Vehicle info bottom
```

### Environment 🌍

```markdown
OS:
- **OS**: Windows 10
- **Graphics**: DX11 (or Vulkan)

Req mods versions:
BepInExPack_Valheim v5.4.2202 by denikson
Jotunn v2.21.3 by ValheimModding
ValheimRAFT v2.4.2 by zolantris

All mods:
BepInExPack_Valheim v5.4.2202 by denikson
AAA_Crafting v1.6.3 by Azumatt
Ancient_Invasion v1.1.1 by coemt
Backpacks v1.3.5 by Smoothbrain
BetterArchery v1.9.8 by ishid4
Blacksmithing v1.3.2 by Smoothbrain
Cooking v1.2.1 by Smoothbrain
EpicLoot v0.10.6 by RandyKnapp
EquipmentAndQuickSlots v2.1.14 by RandyKnapp
Farming v2.2.1 by Smoothbrain
HipLantern v1.0.16 by shudnal
HookGenPatcher v0.0.4 by ValheimModding
Jotunn v2.21.3 by ValheimModding
MistrootTamer v1.0.3 by Azumatt
PlantEasily v2.0.1 by Advize
PlantEverything v1.18.2 by Advize
Quick_Stack_Store_Sort_Trash_Restock v1.4.11 by Goldenrevolver
SeedBed v1.2.4 by blacks7ar
SkilledCarryWeight v1.4.0 by Searica
Slope_Combat_Fix v1.3.0 by lashiernexusmodport
Valweed v420.0.2 by BlackViking
ValheimRAFT v2.4.2 by zolantris
OreMines v1.0.9 by blacks7ar
Biome_Lords_Quest v3.1.1 by TaegukGaming
Seasons v1.4.0 by shudnal
Max_Dungeon_Rooms v2.0.37 by Digitalroot
OdinCampsite v1.5.5 by OdinPlus
CreatureLevelAndLootControl v4.6.2 by Smoothbrain
EpicBossFights v1.0.4 by coemt
SeaAnimals v0.2.7 by Marlthon
Mistlands_Pack_1 v1.0.2 by warpalicious
Plains_Pack_1 v1.0.2 by warpalicious
Swamp_Pack_1 v1.0.4 by warpalicious
Blackforest_Pack_1 v1.0.3 by warpalicious
Meadows_Pack_1 v1.0.4 by warpalicious
Mountains_Pack_1 v1.0.1 by warpalicious
Custom_Raids v1.7.13 by ASharpPen
ServerSideMap v1.3.12 by Mydayyy
Better_Wisps v1.0.42 by Digitalroot
Bounties v3.0.21 by Digitalroot
DetailedLevels v1.3.3 by turbero
Hunting v1.3.7 by blacks7ar
ReportCard v1.3.0 by ComfyMods
CraftFromContainers v3.5.8 by rendl0449
Chain_Manager v1.0.21 by Digitalroot
Triple_Bronze_JVL v1.1.52 by Digitalroot
LootParticlePlus v1.1.7 by blacks7ar
Server_devcommands v1.86.0 by JereKuusela
Upgrade_World v1.62.0 by JereKuusela
Digitalroots_GoldBars v1.2.32 by Digitalroot
```

**Comment by zolantris** [comment]
#159 Fixes this likely.

**Comment by Amaradu** [comment]
Nope, updated to 2.4.3. I know that ship is anchored and cant move. I want to raise the anchor using leftshift or other rebindible hotkey (when I was looking for fix) but I cant. I see the indicator near the map that indicates ship is anchored.

https://streamable.com/dcmdm0

the video shows that anchor key is leftshift and I'm pressing leftshift key, I also tried right shift, control, space...
will try to uninstall r2modman and its files and reinstalling, maybe something is conflicting.

**Comment by Amaradu** [comment]
Found the issue, there was a usb bluetooth adapter plug into pc and it caused the problem.
