### ISSUE TITLE
ValheimRAFT crafting options not appearing after 1.6.1 Update, Previous ValheimRAFT creations being Destroyed/Jumbled

### ISSUE THREAD

**Issue by SanctumEquiti** [zolantris/ValheimMods#18]
Upon updating to 1.6.1, the crafting tab option to make anything using the ValheimRAFT mod with the hammer has completely disappeared, rendering the mod no longer useable or visible at all. Along with this, the update has also caused any previous creations made with the mod to be crumpled up into one little blob or mass of wood and structures, no greater than a meter in height, width, or length. This means that any previous creations are a mess of random building blocks that were once used to create it, all jumbled into one blob, similar in appearance to a crumpled up piece of paper. 
Rolling the mod and server save back to 1.5.2 yields the same blob like result of previous creations, but brings back the same ability to use the mod via the "ValheimRAFT" creation tab using the hammer. 
I'm unaware of any possible solutions to these issues.
The current modlist between my friends and I includes:
  - Dig Deeper
  - The default BepinExPack
  - Expand_World_Rivers
  - ValheimSimpleAutoSort
  - ElementalFalls
  - Jotunn
  - ValheimRAFT

We have not attempted to isolate this mod and recreate this issue. We have only since rolled back to the 1.5.2 version that was working before updating.

**Comment by zolantris** [comment]
Drop down to 1.5.x for now. It's related to not having the PlanBuild plugin which I attempted to patch, but accidently made it a required item.

**Comment by zolantris** [comment]
v1.6.3 or 1.6.4 should both be stable. Give those a try. Closing this for now as most of the item issues were fixed in 1.6.3
