### ISSUE TITLE
船体支离破碎

### ISSUE THREAD

**Issue by feifeid47** [zolantris/ValheimMods#21]
当你离开船很远的距离。如果这个时候游戏保存了。再次回到船所在的位置。船变得支离破碎。
请以更高的优先级修复这个问题。

**Comment by feifeid47** [comment]
machine translation

When you leave the boat for a long time. If the game is saved at this time. Return to the position of the ship again. The ship became fragmented.

Please fix this problem with higher priority.

**Comment by zolantris** [comment]
@feifeid47 Is this on server or single player?

**Comment by feifeid47** [comment]
单人游戏中出现的问题

Problems in single-player games

**Comment by zolantris** [comment]
For your boat. Please run `raftoffset 0 0 0`. This is a workaround fix.

**Comment by zolantris** [comment]
@feifeid47 this issue should be fixed. Your boat will not fragment with `ValheimRAFT-1.6.3`
