### ISSUE TITLE
Need gui feedback on if anchor is deployed

### ISSUE THREAD

**Issue by Nunyabb** [zolantris/ValheimMods#25]
I see new people that are trying the mod for first time think the mod is broke or they installed it wrong when the ship does not move forward. They have no indication they are anchored and need to press the L-Shift key. (trying to find a way to mark this as an enchancement) 
EDIT: Perhaps a simple solution would be something like this so they know a anchor exists. In this screenshot i should have labled it "[L-Shift] Anchor" as right shift does nothing
![Screenshot 2023-12-25 134305](https://github.com/zolantris/ValheimMods/assets/154016630/ca11eb59-efee-4f5e-aa24-f814fe1fc3d7)
I myself had this issue in the beginning. Seeing others have it as well. This is like 4th person ive helped in discord. Example: 
 
![Screenshot 2023-12-25 135217](https://github.com/zolantris/ValheimMods/assets/154016630/b8c918d5-9a32-4be9-bdaf-8c6562ecc9af)

**Comment by zolantris** [comment]
Yeah that or a status effect of anchored

**Comment by zolantris** [comment]
Anchored, probably can be made much less confusing by just letting the user move forwards or backwards even if anchored. I'll probably just add that in the next release. Then fiddle with UI when I can.

**Comment by Nunyabb** [comment]
i kinda like drifing on the water unanchored especially during a storm. but i understand its for simplicity

**Comment by zolantris** [comment]
![Screenshot 2023-12-26 070319](https://github.com/zolantris/ValheimMods/assets/151822540/5e24e1c2-aa6f-44ab-a3fa-71a4d0103ece)
![Screenshot 2023-12-26 070334](https://github.com/zolantris/ValheimMods/assets/151822540/0dffbb16-2f00-4711-893e-5efa3b454294)

ETA 1.6.3

**Comment by zolantris** [comment]
> i kinda like drifing on the water unanchored especially during a storm. but i understand its for simplicity

I won't remove that feature if anything I'll make anchors require materials.

**Comment by Nunyabb** [comment]
you da man good work! Thanks
