### ISSUE TITLE
Rafthide command killing my boat.

### ISSUE THREAD

**Issue by lotsmon** [zolantris/ValheimMods#35]
### What happened?

If you use the true command `rafthide true` and go to the asset unloading area. Then, upon returning on board, the raft falls under the water along with this FPS 1-2. Recommendation: Do not use the raftide true command until the problem is fixed.

### Steps to reproduce

1. Place the raft.
2. Build something on the raft.
3. Write the console command “raftide true”.
4. Use the “fly” command to fly as far as possible from the raft so that the game unloads it.
5. Try to get back on the raft

### Log outputs

```txt
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ShipControlls.GetUser () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
ShipControlls.HaveValidUser () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
Ship.HaveControllingPlayer () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
ValheimRAFT.Patches.ValheimRAFT_Patch.Ship_FixedUpdate (Ship __instance) (at F:/modding/valheim/ValheimRAFT/ValheimRAFT/Patches/ValheimRAFT_Patch.cs:170)
(wrapper dynamic-method) Ship.DMD<Ship::CustomFixedUpdate>(Ship,single,single)
MonoUpdaters.FixedUpdate () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
```

### Environment

```markdown
OS:
- **OS**: Windows 11
- **Graphics**: DX11
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: 1.6.8
```

**Comment by zolantris** [comment]
I'll be adding more guards for setters. Not sure why this would regress, but I can look at it. Are there any other mods you are using?
