### ISSUE TITLE
Plan Build and No Stone Building issue

### ISSUE THREAD

**Issue by jdalfonso4341** [zolantris/ValheimMods#39]
### What happened?

There seems to be an incompatability between plan build and Valheim Raft that is throwing lots of errors. I also cannot figure out how to build stone or black marble ships. This was a default setting on the original raft mod.

### Environment

```markdown
OS:
- **OS**: Windows 11 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: 1.7.0
```

**Comment by zolantris** [comment]
Next patch will fix this. V2.x.x will need to have some discussion about these patches, there's a high chance some are interfering in ways that can break ValheimRAFT.

**Comment by zolantris** [comment]
Also black marble is an a separate issue, the base game texture moves as you change positions. The base texture would need a patch.

You can build black marble ships, and stone, etc but you will need more sails (or to tweak the config).
