### ISSUE TITLE
Anchor does not work in flightmode

### ISSUE THREAD

**Issue by neebux** [zolantris/ValheimMods#40]
### What happened?

Anchor works great while in the water but does not work while in the air, (allowflight config enabled).
The raft just drifts away until stopped by an object, lands on the water or "you deploy the sail " to move again.
The anchoring feature used to work, and achored the raft on previous versions. (1.4.9)
PS Mod is looking great :D

### Environment

```markdown
OS:
- **OS**: Windows 11 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: 1.7.0
```

**Comment by zolantris** [comment]
1.6.9 fixes this.
