### ISSUE TITLE
Initial speed on raft is out of control

### ISSUE THREAD

**Issue by RedekerKane** [zolantris/ValheimMods#41]
### What happened?

I created a raft, added a mast, added a wheel, and when I launched, the speeds were far faster than they should be. Tier 3 speed was out of control fast. This is with default options, tested on a new character, new map, with ValheimRAFT as the only mod.

### Environment

```markdown
OS:
- **OS**: Windows 11 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: 1.7.0
```

**Comment by zolantris** [comment]
Tier 3 on a basic raft is unbalanced. Either update your sail area calcs or use a tier 1 on a small raft. Larger rafts or more weight in a raft will affect speed.

**Comment by zolantris** [comment]
Also if you determine a more balanced values, feel free to submit them here, I'm open to setting them as defaults for the config in the future.
