### ISSUE TITLE
Other mod but i think u can help hahahah

### ISSUE THREAD

**Issue by dominik199818** [zolantris/ValheimMods#46]
### What happened?

![image](https://github.com/zolantris/ValheimMods/assets/155236476/6b73a27a-bb48-4b58-98ad-f20ce5bf9089)
Also making some lag but i dont know from where 

### Steps to reproduce

.

### Log outputs

```txt
.
```

### Environment

```markdown
OS:
- **OS**: Windows 11 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: Major.Minor.Patch
```

**Comment by zolantris** [comment]
That's beds mobile. Remove it and see if you error out. It might not be beds mobile causing the problem but something could have broken it.
