### ISSUE TITLE
Update Borked it 

### ISSUE THREAD

**Issue by N0VA99** [zolantris/ValheimMods#65]
### What happened?

with the newest update to valheim, the Raft mod appears to have completely vanished from the crafting menu along with any ships that previously existed seem to have merged into a mass. I've attempted to revert to previous save to see if that'd help but it did not unfortunately.

### Steps to reproduce

i dunno

### Log outputs

```txt
will occur upon any launch of the game
```

### Environment

```markdown
OS:
- **OS**: Windows 11 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: Major.Minor.Patch
```

**Comment by zolantris** [comment]
>=v2.0.0 should be much more stable. Also in >=2.0.2 you can now recover ANY raft. See #74
