### ISSUE TITLE
Immovable menu near top left corner of the screen blocking inventory, etc

### ISSUE THREAD

**Issue by lzlava** [zolantris/ValheimMods#71]
### What happened?

There's a menu with options like "collider debugger," "raftcreative," "activatePendingPieces," etc. on the mid-top-left corner of my screen the second I start Valheim which stays there after I go in game. I cant interact with the menu and can't move it. It's currently blocking my inventory and is causing some trouble.

### Steps to reproduce

1. Start the game - and it's already there...

### Log outputs

```txt
Not sure about relevant logs
```

### Environment

```markdown
OS:
- **OS**: Windows 11 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.20.0
- **ValheimRAFT**: 2.0.0
```

**Comment by zolantris** [comment]
This should be resolved in #74. The debug menu can be toggled with the Config manager and is by default off.
