### ISSUE TITLE
Version 2.0 of the mod destroys raft builds from 1.x.x

### ISSUE THREAD

**Issue by EXPLTVE** [zolantris/ValheimMods#72]
### What happened?

When loading a world with raft bases from 1.x.x, the raft bases are missing and all build pieces are clumped together in the water. Is it possible to support the old bases in 2.0?

### Log outputs

```txt
Lost log after rolling back to restore old ship build.
```

### Environment

```markdown
OS:
- **OS**: Windows 11
- **Graphics**: DX12 
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.20.2
- **ValheimRAFT**: 2.0.1
```

**Comment by zolantris** [comment]
Not resolved. But easily fixed with `raftrecover confirm` or `vehicle recover` both will convert the broken old raft to the new v2 raft. Up to you if you want to downgrade afterwards.
