### ISSUE TITLE
incompatible with Custom ships

### ISSUE THREAD

**Issue by Dash200017** [zolantris/ValheimMods#84]
https://www.nexusmods.com/valheim/mods/2653?tab=description

Errors pop up in log when placing anything with hammer when both mods are installed

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimRAFT.Patches.Player_Patch.PlacedPiece (Player player, UnityEngine.GameObject gameObject) (at <29ab4afd77064c2cb94779e0be45d334>:0)
(wrapper dynamic-method) Player.DMD<Player::PlacePiece>(Player,Piece)
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacement>(Player,bool,single)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

**Comment by zolantris** [comment]
It should be fine on 2.1.0. Tested it.
