### ISSUE TITLE
Cant deconstruct parts attached to Raft

### ISSUE THREAD

**Issue by m4rcus25** [zolantris/ValheimMods#89]
### What happened?

As Stated in the title, destroy / deconstruct does not work

### Steps to reproduce

build raft -> attach wood floor -> press deconstruct

### Log outputs

```txt
[Error  : Unity Log] MissingMethodException: Method not found: void .WearNTear.Destroy()
Stack trace:
ValheimRAFT.Patches.ValheimRAFT_Patch.WearNTear_Destroy (WearNTear __instance) (at <b1a8bb6cbd4e48819fd47e1d68b1443d>:0)
(wrapper dynamic-method) WearNTear.DMD<WearNTear::Destroy>(WearNTear,HitData)
WearNTear.RPC_Remove (System.Int64 sender) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
RoutedMethod.Invoke (System.Int64 rpc, ZPackage pkg) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
ZNetView.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData rpcData) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
ZNetView.InvokeRPC (System.String method, System.Object[] parameters) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
WearNTear.Remove () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
(wrapper dynamic-method) Player.DMD<Player::RemovePiece>(Player)
Player.UpdatePlacement (System.Boolean takeInput, System.Single dt) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)
```

### Environment

```markdown
OS:
- **OS**: Windows 11 
- **Graphics**: DX11 
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.20.0
- **ValheimRAFT**: 2.1.1
Additional Mods:
- PlantEverything 1.17.3
- FloorsAreRoofs 2.0.2
- FarmGrid 0.5.0
Better Archery 1.9.5
AzuExtendedPlayerInventory 1.4.3
```

**Comment by zolantris** [comment]
Please provide the full player log. That does not look like a v2.0.0 or higher issue. 1.6.14 had this problem.

**Comment by m4rcus25** [comment]
[Message:   BepInEx] BepInEx 5.4.22.0 - valheim (10.04.2024 15:30:10)
[Message:   BepInEx] User is running BepInExPack Valheim version 5.4.2202 from Thunderstore
[Info   :   BepInEx] Running under Unity v2022.3.17.5228416
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 9 plugins to load
[Info   :   BepInEx] Loading [PlantEverything 1.17.3]
[Info   :   BepInEx] Loading [Better Archery 1.9.5]
[Info   : Unity Log] 05/24/2024 17:13:25: Loaded localization file #0 - 'localization' language: 'English'

[Info   : Unity Log] 05/24/2024 17:13:25: Loaded localization file #1 - 'localization_extra' language: 'English'

[Info   : Unity Log] 05/24/2024 17:13:25: Loaded localization file #2 - 'heightmap_message' language: 'English'

[Info   : Unity Log] 05/24/2024 17:13:25: Loaded localization file #3 - 'localization_hildir' language: 'English'

[Info   : Unity Log] 05/24/2024 17:13:25: Loaded localization file #4 - 'localization_emotes' language: 'English'

[Info   : Unity Log] 05/24/2024 17:13:25: Loaded localization file #5 - 'localization_ashlands' language: 'English'

[Info   : Unity Log] 05/24/2024 17:13:25: Loaded localization file #0 - 'localization' language: 'English'

[Info   : Unity Log] 05/24/2024 17:13:25: Loaded localization file #1 - 'localization_extra' language: 'English'

[Info   : Unity Log] 05/24/2024 17:13:25: Loaded localization file #2 - 'heightmap_message' language: 'English'

[Info   : Unity Log] 05/24/2024 17:13:25: Loaded localization file #3 - 'localization_hildir' language: 'English'

[Info   : Unity Log] 05/24/2024 17:13:25: Loaded localization file #4 - 'localization_emotes' language: 'English'

[Info   : Unity Log] 05/24/2024 17:13:25: Loaded localization file #5 - 'localization_ashlands' language: 'English'

[Info   :   BepInEx] Loading [AzuExtendedPlayerInventory 1.4.3]
[Info   :   BepInEx] Loading [Jotunn 2.20.0]
[Info   :Jotunn.Main] Initializing ModCompatibility
[Info   :Jotunn.Main] Initializing SynchronizationManager
[Info   :Jotunn.Main] Initializing NetworkManager
[Info   :   BepInEx] Loading [FarmGrid 0.5.0]
[Info   :   BepInEx] Loading [ValheimRAFT 1.4.9]
[Info   :Jotunn.Main] Initializing CommandManager
[Info   :Jotunn.Main] Initializing PrefabManager
[Info   :   BepInEx] Loading [Floors Are Roofs 2.0.2]
[Info   : Unity Log] [floorsareroofs]: Initializing using config settings: PrefabsToChange:[wood_floor,wood_floor_1x1], Hammers:[Hammer], RemoveRainDamage:[True]
[Info   :Jotunn.Main] Initializing PieceManager
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.2]
[Info   :   BepInEx] Loading [ValheimRAFT 2.1.1]
[Warning:ValheimRAFT.Patches.Teleport_Patch] TeleportWorld patch failed.
[Warning:Jotunn.Managers.CommandManager] [ValheimRAFT] Cannot have two console commands with same name: RaftCreative
[Warning:Jotunn.Managers.CommandManager] [ValheimRAFT] Cannot have two console commands with same name: RaftOffset
[Warning:Jotunn.Managers.CommandManager] [ValheimRAFT] Cannot have two console commands with same name: RaftHide
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Privilege Multiplayer is not known on this platform. Privilege therefore is granted without check...
[Info   : Unity Log] Privilege UserGeneratedContent is not known on this platform. Privilege therefore is granted without check...
[Info   : Unity Log] Privilege CrossPlay is not known on this platform. Privilege therefore is granted without check...
[Info   : Unity Log] 05/24/2024 17:13:27: Set background loading budget to Low

[Info   :Jotunn.Main] Initializing LocalizationManager
[Warning: Unity Log] 05/24/2024 17:13:27: Fetching PlatformPrefs 'GuiScale' before loading defaults

[Warning: Unity Log] 05/24/2024 17:13:27: Fetching PlatformPrefs 'GuiScale' before loading defaults

[Info   : Unity Log] 05/24/2024 17:13:27: Starting to load scene:start.unity (169d7618616154c03be07e9ad3af5893)

[Info   : Unity Log] 05/24/2024 17:13:27: Set background loading budget to Normal

[Info   : Unity Log] 05/24/2024 17:13:31: Set background loading budget to High

[Info   : Unity Log] Joystick connected ("Controller (XBOX 360 For Windows)").
[Info   : Unity Log] 05/24/2024 17:13:53: Set background loading budget to Low

[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Warning: Unity Log] 05/24/2024 17:13:54: Missing audio clip in music respawn

[Info   : Unity Log] 05/24/2024 17:13:54: Using environment steamid 

[Info   : Unity Log] 05/24/2024 17:13:54: Using steam APPID:

Setting breakpad minidump AppID = 892970
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198016104178 [API loaded no]
[Info   : Unity Log] 05/24/2024 17:13:55: Authentication:k_ESteamNetworkingAvailability_Attempting

[Info   : Unity Log] 05/24/2024 17:13:55: Steam initialized, persona:

[Info   : Unity Log] 05/24/2024 17:13:55: PlayFab custom ID set to "Steam_76561198016104178"

[Info   : Unity Log] 05/24/2024 17:13:55: Using default prefs

[Info   : Unity Log] 05/24/2024 17:13:55: Valheim version: 0.218.15 (network version 27)

[Info   : Unity Log] Trying to set graphic mode to 'Custom'
[Info   : Unity Log] Graphic mode 'Custom' is not or no longer supported. Fallback to default mode for platform...
[Info   : Unity Log] Graphic mode 'Custom' applied!
[Info   : Unity Log] 05/24/2024 17:13:55: Worldgenerator version setup:2

[Info   :Jotunn.Managers.CommandManager] Adding 6 commands to the Console
[Info   : Unity Log] 05/24/2024 17:13:55: Render threading mode:MultiThreaded

[Warning: Unity Log] 05/24/2024 17:13:55: Set button "CamZoomIn" to None!

[Warning: Unity Log] 05/24/2024 17:13:55: Set button "CamZoomOut" to None!

[Warning: Unity Log] 05/24/2024 17:13:55: Set button "CamZoomIn" to None!

[Warning: Unity Log] 05/24/2024 17:13:55: Set button "CamZoomOut" to None!

[Info   : Unity Log] 05/24/2024 17:13:55: Checking for installed DLCs

[Info   : Unity Log] 05/24/2024 17:13:55: DLC:beta installed:False

[Warning:Jotunn.EventExtensions] Exception thrown at event InvokeOnVanillaObjectsAvailable in ValheimRAFT.LoadCustomTextures:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\m4rcu\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Valheim\profiles\valheim\BepInEx\plugins\ValheimRAFT\Assets\Sails'.
  at System.IO.Enumeration.FileSystemEnumerator`1[TResult].CreateDirectoryHandle (System.String path, System.Boolean ignoreNotFound) [0x0004d] in <17d9ce77f27a4bd2afb5ba32c9bea976>:0
  at System.IO.Enumeration.FileSystemEnumerator`1[TResult]..ctor (System.String directory, System.IO.EnumerationOptions options) [0x00050] in <17d9ce77f27a4bd2afb5ba32c9bea976>:0
  at System.IO.Enumeration.FileSystemEnumerable`1+DelegateEnumerator[TResult]..ctor (System.IO.Enumeration.FileSystemEnumerable`1[TResult] enumerable) [0x00000] in <17d9ce77f27a4bd2afb5ba32c9bea976>:0
  at System.IO.Enumeration.FileSystemEnumerable`1[TResult]..ctor (System.String directory, System.IO.Enumeration.FileSystemEnumerable`1+FindTransform[TResult] transform, System.IO.EnumerationOptions options) [0x00042] in <17d9ce77f27a4bd2afb5ba32c9bea976>:0
  at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles (System.String directory, System.String expression, System.IO.EnumerationOptions options) [0x00014] in <17d9ce77f27a4bd2afb5ba32c9bea976>:0
  at System.IO.Directory.InternalEnumeratePaths (System.String path, System.String searchPattern, System.IO.SearchTarget searchTarget, System.IO.EnumerationOptions options) [0x0003c] in <17d9ce77f27a4bd2afb5ba32c9bea976>:0
  at System.IO.Directory.GetFiles (System.String path, System.String searchPattern, System.IO.EnumerationOptions enumerationOptions) [0x00000] in <17d9ce77f27a4bd2afb5ba32c9bea976>:0
  at System.IO.Directory.GetFiles (System.String path) [0x0000b] in <17d9ce77f27a4bd2afb5ba32c9bea976>:0
  at ValheimRAFT.CustomTextureGroup.Load (System.String groupName) [0x0004a] in <b1a8bb6cbd4e48819fd47e1d68b1443d>:0
  at ValheimRAFT.ValheimRAFT.LoadCustomTextures () [0x00001] in <b1a8bb6cbd4e48819fd47e1d68b1443d>:0
  at Jotunn.EventExtensions.SafeInvoke (System.Action events) [0x00018] in D:\Projects\Jotunn\JotunnLib\Extensions\EventExtensions.cs:26
[Info   :Jotunn.Main] Initializing AssetManager
[Info   :Jotunn.Main] Initializing MockManager
[Warning:Jotunn.Managers.PrefabManager] Failed to clone prefab, name already exists: MBRaft
[Warning:Jotunn.EventExtensions] Exception thrown at event InvokeOnVanillaObjectsAvailable in ValheimRaftPlugin.AddCustomPieces:
System.NullReferenceException: Object reference not set to an instance of an object
  at ValheimVehicles.Prefabs.Registry.RaftPrefab.GetTransformedRaft () [0x00014] in <aeea5989670e4226977ebe4543ad24cb>:0
  at ValheimVehicles.Prefabs.Registry.RaftPrefab.Register (Jotunn.Managers.PrefabManager prefabManager, Jotunn.Managers.PieceManager pieceManager) [0x00000] in <aeea5989670e4226977ebe4543ad24cb>:0
  at ValheimVehicles.Prefabs.PrefabRegistryController.RegisterAllPrefabs () [0x00000] in <aeea5989670e4226977ebe4543ad24cb>:0
  at ValheimVehicles.Prefabs.PrefabRegistryController.Init () [0x000be] in <aeea5989670e4226977ebe4543ad24cb>:0
  at ValheimRAFT.ValheimRaftPlugin.AddCustomPieces () [0x0001a] in <aeea5989670e4226977ebe4543ad24cb>:0
  at Jotunn.EventExtensions.SafeInvoke (System.Action events) [0x00018] in D:\Projects\Jotunn\JotunnLib\Extensions\EventExtensions.cs:26
[Info   : Unity Log] [PrefabCreator] Skipped recipe: Recipe_LeatherQuiver
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_ArrowWoodAnywhere
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_FireArrowTransform
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_PoisonArrowTransform
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_SilverArrowTransform
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_FrostArrowTransform
[Info   : Unity Log] 05/24/2024 17:13:56: Sending PlayFab login request (attempt 1)

[Info   : Unity Log] 05/24/2024 17:13:56: Starting music menu

[Info   : Unity Log] 05/24/2024 17:13:57: PlayFab logged in as "Steam_76561198016104178"

[Info   : Unity Log] 05/24/2024 17:13:57: PlayFab local entity ID is 1ED322FA35E5198F

[Info   : Unity Log] 05/24/2024 17:13:59: show character selection

[Info   : Unity Log] 05/24/2024 17:14:00: OnCharacterStart

[Info   : Unity Log] 05/24/2024 17:14:15: Loading main scene

[Info   : Unity Log] 05/24/2024 17:14:15: Audioman already exist, destroying self

[Info   : Unity Log] 05/24/2024 17:14:15: Steam initialized, persona:

[Info   : Unity Log] 05/24/2024 17:14:15: PlayFab custom ID set to "Steam_76561198016104178"

[Info   : Unity Log] 05/24/2024 17:14:15: Using default prefs

[Info   :Jotunn.Managers.CommandManager] Adding 6 commands to the Console
[Info   : Unity Log] 05/24/2024 17:14:15: Loading player profile marcus

[Info   : Unity Log] 05/24/2024 17:14:15: isModded: True

[Info   : Unity Log] 05/24/2024 17:14:15: Zonesystem Awake 4784

[Info   : Unity Log] 05/24/2024 17:14:15: DungeonDB Awake 4784

[Info   : Unity Log] 05/24/2024 17:14:15: Steam initialized, persona:

[Info   : Unity Log] 05/24/2024 17:14:15: Worldgenerator version setup:2

[Info   : Unity Log] Registered 'advize.PlantEverything ConfigSync' RPC - waiting for incoming connections
[Info   : Unity Log] Registered 'Azumatt.AzuExtendedPlayerInventory ConfigSync' RPC - waiting for incoming connections
[Info   :Jotunn.Managers.PrefabManager] Adding 16 custom prefabs to the ZNetScene
[Info   : Unity Log] 05/24/2024 17:14:18: Checking for installed DLCs

[Info   : Unity Log] 05/24/2024 17:14:18: DLC:beta installed:False

[Info   : Unity Log] [PrefabCreator] Skipped recipe: Recipe_LeatherQuiver
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_ArrowWoodAnywhere
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_FireArrowTransform
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_PoisonArrowTransform
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_SilverArrowTransform
[Info   : Unity Log] [PrefabCreator] Added recipe: Recipe_FrostArrowTransform
[Info   :Jotunn.Managers.PieceManager] Adding 15 custom pieces to the PieceTables
[Info   : Unity Log] [floorsareroofs]: Triggered from PieceManager_OnPiecesRegistered
[Info   : Unity Log] [floorsareroofs]: Beginning patch attempt
[Info   : Unity Log] [floorsareroofs]: Starting to patches pieces in Hammer Hammer.
[Info   : Unity Log] [floorsareroofs]: Preparing to patch wood_floor_1x1
[Info   : Unity Log] [floorsareroofs] Successfully patched wood_floor_1x1 into a roof
[Info   : Unity Log] [floorsareroofs] wood_floor_1x1 patched to not degrade in the rain
[Info   : Unity Log] [floorsareroofs]: Preparing to patch wood_floor
[Info   : Unity Log] [floorsareroofs] Successfully patched wood_floor into a roof
[Info   : Unity Log] [floorsareroofs] wood_floor patched to not degrade in the rain
[Info   : Unity Log] [floorsareroofs]: Finished with hammer Hammer.  Sucessfully updated 2 floors.
[Info   : Unity Log] [floorsareroofs]: Successfully updated 2 floors.  Config setting has 2 floors specified.
[Info   : Unity Log] [floorsareroofs]: Floors updated finished successfully.
[Info   :Jotunn.Managers.NetworkManager] Registering 2 custom RPCs
[Info   : Unity Log] 05/24/2024 17:14:18: Zonesystem Start 4784

[Info   : Unity Log] 05/24/2024 17:14:18: Added 3 locations, 0 vegetations, 0 environments, 0 biome env-setups, 0 clutter  from main

[Info   : Unity Log] 05/24/2024 17:14:18: Added 1 locations, 0 vegetations, 2 environments, 0 biome env-setups, 0 clutter  from main

[Info   : Unity Log] 05/24/2024 17:14:18: Added 27 locations, 25 vegetations, 5 environments, 1 biome env-setups, 3 clutter  from main

[Info   : Unity Log] 05/24/2024 17:14:18: Added 4 locations, 0 vegetations, 1 environments, 0 biome env-setups, 0 clutter  from main

[Info   : Unity Log] 05/24/2024 17:14:18: Added 24 locations, 33 vegetations, 8 environments, 2 biome env-setups, 2 clutter  from main

[Info   : Unity Log] 05/24/2024 17:14:18: DungeonDB Start 4784

[Info   : Unity Log] 05/24/2024 17:14:18: ZRpc timeout set to 30s

[Info   : Unity Log] 05/24/2024 17:14:18: ZNET START

[Info   : Unity Log] 05/24/2024 17:14:18: Load world: SuperAsh (SuperAsh)

[Info   : Unity Log] 05/24/2024 17:14:18: Loading 8578 zdos, my sessionID: 2311374555, data version: 34

[Info   : Unity Log] 05/24/2024 17:14:18: Loading in ZDOs

[Info   : Unity Log] 05/24/2024 17:14:18: Adding to Dictionary

[Info   : Unity Log] 05/24/2024 17:14:18: Adding to Sectors

[Info   : Unity Log] 05/24/2024 17:14:18: Connecting Portals, Spawners & ZSyncTransforms

[Info   : Unity Log] ConnectSpawners => Connected 0 spawners and 1 'done' spawners.
[Info   : Unity Log] 05/24/2024 17:14:18: Loaded 11386 locations

[Info   : Unity Log] 05/24/2024 17:14:18: Unloading unused assets

[Info   : Unity Log] Am I Host? True
[Info   : Unity Log] 05/24/2024 17:14:18: Starting respawn

[Info   : Unity Log] 05/24/2024 17:14:19: Loading minimap textures done [326ms]

[Info   : Unity Log] 05/24/2024 17:14:19: Minimap: unpacking compressed mapData 8245 => 8388617 bytes

[Info   : Unity Log] 05/24/2024 17:14:19: tip:$loadscreen_tip07

[Info   : Unity Log] 05/24/2024 17:14:22: Force generating hmap (64.00, 0.00, 0.00)

[Info   : Unity Log] 05/24/2024 17:14:22: Force generating hmap (64.00, 0.00, 64.00)

[Info   : Unity Log] 05/24/2024 17:14:22: Activating MBRoot: -1464446989

[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: 1959580535
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
ZNetView.Register[T] (System.String name, System.Action`2[T1,T2] f) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
ValheimRAFT.MoveableBaseShipComponent.Awake () (at <b1a8bb6cbd4e48819fd47e1d68b1443d>:0)
UnityEngine.GameObject:AddComponent()
ValheimRAFT.Patches.Ship_Patch:Ship_Awake(Ship)
Ship:DMD<Ship::Awake>(Ship)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ZNetScene:CreateObject(ZDO)
ZNetScene:CreateObjectsSorted(List`1, Int32, Int32&)
ZNetScene:CreateObjects(List`1, List`1)
ZNetScene:DMD<ZNetScene::CreateDestroyObjects>(ZNetScene)
ZNetScene:Update()

[Info   : Unity Log] 05/24/2024 17:14:27: Spawned after 8,019994

[Info   : Unity Log] 05/24/2024 17:14:27: Skipping unloading unused assets

[Info   : Unity Log] 05/24/2024 17:14:27: Minimap: Adding unique location (-3.04, 33.53, -1.46)

[Info   : Unity Log] 05/24/2024 17:14:29: Starting music meadows

[Info   : Unity Log] 05/24/2024 17:14:29: Resumed music meadows at 0

[Error  : Unity Log] MissingMethodException: Method not found: void .WearNTear.Destroy()
Stack trace:
ValheimRAFT.Patches.ValheimRAFT_Patch.WearNTear_Destroy (WearNTear __instance) (at <b1a8bb6cbd4e48819fd47e1d68b1443d>:0)
(wrapper dynamic-method) WearNTear.DMD<WearNTear::Destroy>(WearNTear,HitData)
WearNTear.RPC_Remove (System.Int64 sender) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
RoutedMethod.Invoke (System.Int64 rpc, ZPackage pkg) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
ZNetView.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData rpcData) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
ZNetView.InvokeRPC (System.String method, System.Object[] parameters) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
WearNTear.Remove () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
(wrapper dynamic-method) Player.DMD<Player::RemovePiece>(Player)
Player.UpdatePlacement (System.Boolean takeInput, System.Single dt) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

**Comment by zolantris** [comment]
This looks like a bad install. Closing this. Installation of the full mod must be within the plug-ins folders. The folder should be named ValheimRAFT and within it should be the mods + assets folder.
