### ISSUE TITLE
Compatibility with ComfyGizmo

### ISSUE THREAD

**Issue by rameils** [zolantris/ValheimMods#98]
### What happened?

After building and moving the ship, the rotation never returns to the default rotation when using the 'raftcreative' or 'vehicle creative' command. Ultimately, any pieces you place after moving the ship will be off rotation relative to the ship's rotation. This causes major building and symmetry issues with pieces becoming off rotation by small or sometimes major increments. I believe the older versions of this mod reset the rotation to default rotation increments while in creative mode. While this did rotate the boat in creative mode, it allowed you to build with the proper rotation and wasn't much of an issue unless you built close to the shore.

Please add an option to allow rotation to be reset completely while in creative mode. This can be used as a temporary fix to using this rotation mod; I was not fortunate enough to find any other updated and compatible rotation mod. The copy rotation on ComfyGizmo allows me to copy the old rotation but I don't believe it's ideal and is not always working 100%(Copy's either local or global rotation and sometimes causes issues).

Reference: https://github.com/zolantris/ValheimMods/issues/28

### Steps to reproduce

1. Create new boat vehicle
2. Raise with 'raftcreative' or 'vehicle creative'
3. Build pieces and wheel/rudder to move
4. Move/rotate boat any amount
5. Raise with 'raftcreative' or 'vehicle creative' and attempt building(you will see rotation is off).

### Log outputs

```txt
No logs
```

### Environment

```markdown
OS:
- **OS**: Windows 10
- **Graphics**: DX11
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: 2.1.1
- ComfyGizmo 1.92
```

**Comment by zolantris** [comment]
Done. Closing this for now. vehicle rotate and vehicle creative now allow for this. 

Adding further compatibility for relative rotation might be a bit too complicated to deliver
